# 1. Import Libraries

In [1]:
!pip install transformers datasets 'accelerate>=1.1.0'
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer
from datasets import Dataset
import pandas as pd
import torch

Requirement already satisfied: transformers in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (5.7.0)
Requirement already satisfied: datasets in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (4.8.5)
Requirement already satisfied: accelerate>=1.1.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (1.13.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from transformers) (1.12.2)
Requirement already satisfied: numpy>=1.17 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from transformers) (2.4.4)
Requirement already satisfied: packaging>=20.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from datasets) (3.0.2)
Requirement already satisfied: requests>=2.32.2 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from datasets) (2.33.1)
Requirement already satisfied: xxhash in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from datasets) (0.70.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: psutil in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from accelerate>=1.1.0) (7.2.2)
Requirement already satisfied: torch>=2.0.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from accelerate>=1.1.0) (2.11.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: setuptools<82 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (13.2.0)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.85)
Requirement already satisfied: cuda-pathfinder~=1.1 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from cuda-bindings<14,>=13.0.3->torch>=2.0.0->accelerate>=1.1.0) (1.5.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from jinja2->torch>=2.0.0->accelerate>=1.1.0) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from typer->transformers) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from typer->transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip

/home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# 2. Load Model

In [2]:
model_name = "w11wo/indonesian-roberta-base-sentiment-classifier"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 3207.80it/s]

# 3. Prepare Dataset

In [12]:
df = pd.read_csv("../dataset/dataset.csv")

labels_map = {
    "Positive": 2,
    "Netral": 1,
    "Negative": 0
}

df["manual_sentiment_mapped"] = df["Manual Sentiment"].map(labels_map)
df

,URL,Judul,Konten,Manual Sentiment,manual_sentiment_mapped
0,https://www.cnbcindonesia.com/research/2025012...,Trump Sebar Exceutive Order: Emang Semengerika...,"Jakarta, CNBC Indonesia -Amerika Serikat (AS) ...",Positive,2
1,https://www.cnbcindonesia.com/research/2025012...,"Alasan Rupiah 'Berpesta' di Pelantikan Trump, ...","Jakarta, CNBC Indonesia -Nilai tukar rupiah te...",Positive,2
2,https://www.cnbcindonesia.com/research/2025012...,"Trump Beri Kabar Baik, Saatnya Menunggu Dolar ...","Jakarta, CNBC Indonesia-Pasar keuangan Indones...",Positive,2
3,https://www.cnbcindonesia.com/research/2025030...,"IHSG Merah Lagi, Begini Penjelasan dari Analis...","Jakarta, CNBC Indonesia -Indeks Harga Saham Ga...",Negative,0
4,https://indodax.com/academy/bitcoin-200k-predi...,Bernstein: Bitcoin Bisa Naik 2x Lipat! Target ...,HargaBitcoin(BTC)pernah melewati angka terting...,Positive,2
...,...,...,...,...,...
996,https://voi.id/teknologi/489452/produsen-mesin...,Produsen Mesin Bitcoin China Pindahkan Produks...,JAKARTA - Tiga produsen mesin penambang bitcoi...,Positive,2
997,https://www.liputan6.com/bisnis/read/6058462/d...,Donald Trump Kembali Tekan Ketua The Fed Jerom...,Presiden Amerika Serikat (AS) Donald Trump men...,Netral,1
998,https://kabar24.bisnis.com/read/20250622/19/18...,"Donald Trump Serang Iran, Ekonomi Global Bakal...","Bisnis.com,JAKARTA — Serangan Amerika Serikat ...",Negative,0
999,https://www.cnbcindonesia.com/tech/20250620153...,Trump 'Palak' Raksasa Teknologi Rp 900 Triliun...,"Jakarta, CNBC Indonesia -Perusahaan semikonduk...",Negative,0
1000,https://www.cnbcindonesia.com/news/20250628200...,Tarif Trump Pukul Jatuh Industri Otomotif Ingg...,"Jakarta, CNBC Indonesia -Kebijakan tarif Presi...",Negative,0

# 4. Tokenise Data

In [14]:
encodings = tokenizer(
    df["Konten"].tolist(),
    truncation=True,
    padding="max_length",
    max_length=128
)

df["input_ids"] = encodings["input_ids"]
df["attention_mask"] = encodings["attention_mask"]
df

,URL,Judul,Konten,Manual Sentiment,manual_sentiment_mapped,input_ids,attention_mask
0,https://www.cnbcindonesia.com/research/2025012...,Trump Sebar Exceutive Order: Emang Semengerika...,"Jakarta, CNBC Indonesia -Amerika Serikat (AS) ...",Positive,2,"[0, 6758, 16, 35210, 7778, 622, 824, 26975, 44...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,https://www.cnbcindonesia.com/research/2025012...,"Alasan Rupiah 'Berpesta' di Pelantikan Trump, ...","Jakarta, CNBC Indonesia -Nilai tukar rupiah te...",Positive,2,"[0, 6758, 16, 35210, 7778, 622, 824, 20028, 11...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,https://www.cnbcindonesia.com/research/2025012...,"Trump Beri Kabar Baik, Saatnya Menunggu Dolar ...","Jakarta, CNBC Indonesia-Pasar keuangan Indones...",Positive,2,"[0, 6758, 16, 35210, 7778, 40175, 7753, 17, 21...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,https://www.cnbcindonesia.com/research/2025030...,"IHSG Merah Lagi, Begini Penjelasan dari Analis...","Jakarta, CNBC Indonesia -Indeks Harga Saham Ga...",Negative,0,"[0, 6758, 16, 35210, 7778, 622, 824, 36568, 29...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,https://indodax.com/academy/bitcoin-200k-predi...,Bernstein: Bitcoin Bisa Naik 2x Lipat! Target ...,HargaBitcoin(BTC)pernah melewati angka terting...,Positive,2,"[0, 5620, 34950, 12, 38, 9786, 13, 38933, 3888...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
...,...,...,...,...,...,...,...
996,https://voi.id/teknologi/489452/produsen-mesin...,Produsen Mesin Bitcoin China Pindahkan Produks...,JAKARTA - Tiga produsen mesin penambang bitcoi...,Positive,2,"[0, 11178, 824, 10177, 5159, 1740, 23062, 7542...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
997,https://www.liputan6.com/bisnis/read/6058462/d...,Donald Trump Kembali Tekan Ketua The Fed Jerom...,Presiden Amerika Serikat (AS) Donald Trump men...,Netral,1,"[0, 14312, 2502, 4439, 423, 2544, 13, 19359, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
998,https://kabar24.bisnis.com/read/20250622/19/18...,"Donald Trump Serang Iran, Ekonomi Global Bakal...","Bisnis.com,JAKARTA — Serangan Amerika Serikat ...",Negative,0,"[0, 11654, 18, 1003, 16, 11178, 7662, 24805, 2...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
999,https://www.cnbcindonesia.com/tech/20250620153...,Trump 'Palak' Raksasa Teknologi Rp 900 Triliun...,"Jakarta, CNBC Indonesia -Perusahaan semikonduk...",Negative,0,"[0, 6758, 16, 35210, 7778, 622, 824, 12295, 45...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1000,https://www.cnbcindonesia.com/news/20250628200...,Tarif Trump Pukul Jatuh Industri Otomotif Ingg...,"Jakarta, CNBC Indonesia -Kebijakan tarif Presi...",Negative,0,"[0, 6758, 16, 35210, 7778, 622, 824, 25206, 64...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

# 5. Convert to Torch

In [15]:
input_ids = torch.tensor(encodings["input_ids"])
attention_mask = torch.tensor(encodings["attention_mask"])
labels = torch.tensor(df["manual_sentiment_mapped"].values).long()

train_dataset = [
    {
        "input_ids": input_ids[i],
        "attention_mask": attention_mask[i],
        "labels": labels[i]
    }
    for i in range(len(labels))
]
train_dataset

[{'input_ids': tensor([    0,  6758,    16, 35210,  7778,   622,   824, 26975,  4439,   423,
           2544,    13,   617,  1781,   530,  2982,   729,   287, 10126,  2659,
            468,  7615,   477,    17, 21979,   287, 21860,    18,   203, 14312,
           2502,  4439,   423,  2544,    13, 19359, 11173,  1781, 13738,   403,
           5329,   698,  2534,   423,  2955,    19,    21,    19,  2955,  4552,
            765,   203,  6675,  1128,    16,   395, 30873,    16, 11173,  4202,
           3057,  4140, 17364,  4059,   287,  1218, 15940,   385,   778,   617,
          12094,  6274,   385,  4958,   458, 22776,    18,   203,  7796,  1059,
           1789,  7615, 29285,  4769, 12414,  4140,    16, 21480,    16, 36492,
           4235,    16,   296,  3598, 35185,    18, 12300,   330,  7653,  1542,
           1705, 18389,  2534,    16,   953,   406, 11376,  6771, 11668,   287,
            429,  4448,  3983,    16, 15743,    16,   296,  4094,  2512, 13747,
           2534,   423,  8016, 11578,    13, 10418,  4845,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(2)},
 {'input_ids': tensor([    0,  6758,    16, 35210,  7778,   622,   824, 20028, 11601,  3818,
           1027,  6826,  2502,  4439,   423,  2544,    13,  2958, 16972,   834,
          19359, 11173, 13738,   525,  2982,  2534,  1850,  1524,  3813,   423,
           2955,    19,    21,    19,  2955,  4552,   765,   203, 17127,   346,
             54,  4834,   301,  1592,    16,  3818,   403,  7887,  4140,   694,
            330,   423,  5394,    19,    21,    19,  2955,  4552,    13, 16972,
           1607,    16,  9627,     9,   283,  2234,  1181,  4250,    18, 48402,
             19,  4064,     8,    18, 13020,   330,   767,   287, 17793,  1421,
           2783,  4582, 36992,   419,  1030,   519,  4225,  1715,    18,   203,
           1758,   535,   287,  5751,    16,  2958, 11649,  6826,  2534,   423,
             40, 45256,    13,  1392,  1019,  5936,  1879,  1607,    16, 14701,
              9,   403,  2727,  1315,    30, 12007,  4167,   346,  2234, 27440,
             16,  7130,   463, 29161,    16,  9310,    18,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(2)},
 {'input_ids': tensor([    0,  6758,    16, 35210,  7778, 40175,  7753,    17, 21288,  2722,
            622, 16972,  6603, 16169, 19359, 11173,   525,  2982,  2502,  4439,
            423,  2544,   765, 19431,  2928, 18225, 28369,   296,  1515, 11601,
           3818,   757,    17,  2416, 16972,  2320,  6610,   930,  3467,  3218,
            423, 15783,    50,    13, 16903,  6077,    18,   203, 21288,  2722,
            622,   694,   330,  2933,   932,  2659,    18, 11233,  1294, 21309,
            296, 23334,  1723,  2722,   622,   403,   694,   330,   383,  6805,
            403,  2510,   711,  1593,   330,    18,   203, 17127,   346,    54,
           4834,   301,  1592,    16,  3818,   403,  4140,  3813,    16,  5498,
            423,  5394,    19,    21,    19,  2955,  4552,    13, 16972,  1607,
             16,  3929,     9,   283,  2234,  1181,  4250,    18, 41118,    19,
           4064,     8,    18,  1363,   463,  1803, 17793,  1421,  2783,  4582,
          36992,   419,   395, 23072,  1715,    18,  1462,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(2)},
 {'input_ids': tensor([    0,  6758,    16, 35210,  7778,   622,   824, 36568,  2928, 18225,
          28369,   423,    45, 25660,    13,   932, 26764,   458,   346,   456,
              9,   296,   932,   316,  4304, 20130,  1550,   563,    18,   203,
             45, 25660,   403,  4140,  5498,   694,   330,   423,    24,    19,
             23,    19,    22,    19,  2955,  4552,    13,  5637, 31320,   456,
             16,  4898,     9,   316,  4304,  1228,    18,    23,  4989,    16,
             24,    18,   203, 25569, 37997,  2145,    16,  2977,    22,  2254,
             16,   296,  8498,    24, 38026,    18,  8515,  2740,   694,   330,
           1632,  1181,  4396,    16,  4552,  5663,   287,  4885,  1918,    16,
           6962,  3908,  3983,   395,   465,    16,  4841,  1898,  2740,    18,
            203,  5898,  4212, 10226,   676, 47213, 21518, 12767,   283,  7803,
           2523,    18, 46425,  1174,  6773,  6526,  2254,  1355,    16, 10151,
           8693, 33098,  2254,   902,    16, 21432,  8693,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(0)},
 {'input_ids': tensor([    0,  5620, 34950,    12,    38,  9786,    13, 38933,  3888,  2234,
           4740,   283,  6327,   342,     8,  7354,    18,  1164,    18,  1172,
            330,  1257,  6771, 17020,   735,  1564, 27645,   385,  2872,  4574,
            287,   458,   660,   662,    18,  1795,  1069,   346, 16485, 31862,
           2045,  5273,   532,   330,   803,  4574,   346,  8714, 35319,    18,
            203,  6310, 12194,  6326,   645,   383,  2145,   856,     8,  4419,
             18,  1164,  2263,   958, 36992,    16, 13026,   488,  4631,  9115,
            766,   296,   779,  2258, 21228, 31700,    18,  2719,    16,   535,
            330, 34950,   645,   762,   275,  2132,  8779,   763,     8, 20853,
             47,   807,  3839, 18899,    47,    18,   203, 16641,  8077,    30,
          31919, 35089, 28464,   203, 17902,  2258,  1468,  9497,   385,   463,
          39409,   700,  5676,   763,  6326,    18,  2126,  2151,   401, 10080,
          43611,  3900,  9115,   766,  1609,  1085,   660,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(2)},
 {'input_ids': tensor([    0,  6758,    16, 35210,  7778,   622,    17,  2982,  8280, 21271,
            772,  3496,  1956, 26258,  3057,  1900,  2982,  2502,  4439, 19359,
          11173,  1984,  6423,  8185,  4140,    18,  1172,   481, 21980,  8280,
            395,  7652,   327,  4476, 14100,  8220,   283, 19769, 14107,   283,
          27820,  4344,    16,  1597,  4997,    16,  1585,  2257,    16,  3813,
             18,   203,  1813, 46153,    16,  2070,  1136,   368, 30136,  3961,
           1429,   287,   385,  5515,  2835,  1895,   919,    18,  9194,   287,
           3677,  1061,   505, 23648,    16,  3500,    16, 46223,    16,   296,
          16969,  3152,  2907,  1429,   468,   330,  6371,  1777,    18,  1386,
            464,   385,  3168,  1116,   887,    18,  2208,   538,  3583,  1127,
           1723,   729,    18,  2208,   330,  1360,  1360, 21630,   406,  1451,
           3400,  8280,    18,  4709,  2505,    16,   998,   330,   622,  3251,
            296, 17154,  1027,  1242,  7850,  2534,  2270,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(0)},
 {'input_ids': tensor([    0, 25206,  6423,  8185,   729,   287,  4522,  2982,  2502,  4439,
          19359, 11173,  4836, 26891,  1723,  3983,   622,    18,  1462,  7887,
           4140,  5551,   389,  5498,   423,    28,    19,    24,    13, 27639,
           2254,   856,  1619,     9,   856, 14584,  8508,   622, 21700, 24777,
          45398,  2320,  4140,  3983,   419,  3233,   569,    88,    18,   203,
          25206,   729,  6423,  8185, 11173,   386, 11358,  3099,  2825,   403,
           1619,  4751, 36992,    18,  3092,   649,   519,  6193,  9976,  2534,
             16,   622,   406,  3343,  3961,  3057,  2982, 11173,   327,  6423,
           8185,  1879,  6330,  5268,   203,  1758,  1850, 11736,   330,    16,
           3386,  8879,  2168,  3340, 16922,  2523,   541,  8037, 19586,   423,
          41115,  7861,    13,  4836,  1748,  3421,   327,   295,  1431,  3983,
           3983, 42944,  1340,   296,  2252, 12160,  3743,  1635,   871,   649,
            763, 40175,    12,  7894,    90,   482,   424,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(0)},
 {'input_ids': tensor([    0, 23226,  8511,  2982,    40, 15799,  1867,   334,   713,   322,
          23469,  4803,  6423,  1027,  1510,   660,  1136,  6193,  9976,  2534,
            772,  3961,   660,   283,  1723,  5334,    18,  1442,   698,  3533,
             16,  1723,  3983,  2534, 19184,    16,   453,   432,   797,  1631,
           6326,   423,    38,  9786,    13,   694,   330, 17559, 15227, 25124,
            763,   287,  5241,    18,   203, 34950,    16,   287,  1218,  1392,
          27939,   763,    16,  1817,  1800,  2701,    17,  7625, 15117,   283,
           1850, 27988,  1723,   287, 13457,    18,   203,  6559,  5343,  6625,
           1363,    30, 34950, 32188,    16, 11729, 14295, 14595, 25492,  7594,
             30,  1587,  2725,    35,   203,  7796,  1059,  7345, 49557,  6423,
            998,  5886,   694,   403,  1619,  4751, 36992,    18,  6308,  3983,
           2534,  2472, 25124,  1106,  1177,    18,    55,    10,    52,  5534,
             16,  7308,   326,    85,    16,   296,   367,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(2)},
 {'input_ids': tensor([    0, 11654,    18,  1003,    16, 13387,   824, 12300,  6423, 11173,
            573,   622,   853, 10003,  1723,  3430,    18,  3480,  8907,  2502,
           4439,  1027,  4140,  6350,  3080,   368,  1360,   660,    16,   717,
           2959,  5268,   225,   203,   203,  2987,   386,   406, 31378,   488,
           1373,  4398,  4905, 21594,   423, 36941,   765,  6561,  3340,  2235,
             16,  8695,  4104,  1216,  1260,   316,  3962,  8682,   296,  3882,
           2870,  1223,  1556,    17,  1701,  1879,  1986,    16,    25,     9,
            296,  1619,    16,    23,     9,   403, 16848,  1005,  1918,  5356,
           2183,  3811,   287,   757,   563,  1218,    18,   225,   203,   203,
           3489,  5368, 20885,  8025, 33731,  7145,  3980,   437,  1315,  2713,
           3430,   287,   463,  2702,  6193,  5429,    18,   225,   203,   203,
           1758,   535,   287,   757,    16,   622,   383,  4629,   863,   327,
           5550,   468,  2982,  2534, 19359, 11173, 11100,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(2)},
 {'input_ids': tensor([    0,  6758,    16, 35210,  7778,   622,    17,  2932,  2929, 20257,
           5606,  1624,  4504,   395,  2102,   423, 21638, 23336,    13,   338,
            712,  8185,   346,  2502,  4439,   572,  9909,  1170,   346,  4212,
           2835,  1849,    16,   997,    16,   296,  3147,   419, 38170,    18,
            203,    54,   290, 49301,  7861, 23336,   338,  1170,  2835, 38170,
            346,  2534,   330,   463,   813,   346,  3057,   287,   385,  4228,
           1540,   338, 15207,  6423,  4140,   287,  6402,  2982,  2534, 19359,
          11173,   316,   622,  1879,  6330,  5268,  1953,  6942,   386, 15356,
            283, 18842, 15424,   403,  2717,    17,  5474,  4751, 36992,  3152,
          21638, 23336,   287, 10589,   327, 38170,  1451,   988,  4755, 20885,
           8025, 33731, 19229, 14848,  6991,   283,  2283,  7035,  7562, 33731,
             16,  1265,  4905,    16,  5329,   423,  4898,    19,    24,    19,
           2955,  4552,   765, 24129,  4874,   406,  4587,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(1)},
 {'input_ids': tensor([    0,    59, 28191,  7218,    56,  3575, 15424,    18,  2042,    37,
           7624,    18,  7520,    37,  5299,  2932,  3761, 15578,  4755, 20885,
           8025, 33731, 19229, 14848,  6991,   996,  9139, 15534,  3761,    16,
            834,  2662,   909,  4266, 37141, 27021,   302,   310, 31386,   263,
            346,  5389, 15592,   302, 10962,  4591,   976,   432,  7665,   423,
           4064,  9807,    13,  9333,  1505,  3298,   996, 10814, 15207,  6423,
            768,  1170,    17,  5703,   287, 30436,   316,  2502,  4439,    18,
            203,  7753,   463,   649,   519,   346,  1194,  1136,   287,   634,
           3318,   617,  1781,   488,  3220,  9807,    16,   338,  2839, 15207,
            395,  8457,  6423,  4140,    16,  2326,   395, 18006,  3058,  5429,
            346, 40978, 12300, 21995,  2846,   534, 10596,   277,  2502,  4439,
            423,  2544,    13,  1027,   622,    18,   203, 10991,  3761, 15578,
           4755, 20885,  8025, 33731, 19229, 14848,  6991,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(2)},
 {'input_ids': tensor([    0,    59, 28191,  7218,    56,  3575, 15424,    18,  2042,    37,
           7624,    18,  7520,    37,  5299,  7753,  6827,   395,   698,  4863,
            694,   429, 31472,   225, 40175, 26808,    16,  8452,   296,  2969,
          15207,  2485,  6423,   395,  4140,   327,  2502,  4439,   423,  2544,
            765,   203, 18695,   386,  4587,  4755, 20885,  8025, 33731, 19229,
          14848,  6991,   834,  3335,   283,  1624,  4755,  1061,  9139, 15534,
           3761,   327,  1328,  3220,  9807,   287,   909,  7125,  4266, 37141,
          27021,   302,   310, 31386,   263,   403,  5222,   423,  4841,    19,
          12111,   765,   203, 13466,  2180,    16,   403,  3335,  1624,  4755,
            481,    16,  1193,  1328,   634,  9333,   338,  1505,  3298,   617,
          13752,  1086, 15207,  6423,   296,  4629, 11911,  1184,   757,    16,
            296, 11503,   338,  3735, 11702,   395,  3589,   698,  4863,   694,
            316,  1279,    18,   203,   944,  9869, 20487,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(2)},
 {'input_ids': tensor([    0,  6758,   423, 30546,    13,   824,  6270,  1005,   814, 21090,
            863,   525,  5206,  2502,  4439,   403,  2419,    16, 19359, 11173,
           5208,  1596,   525,   502,   287,  1821, 19619,    18,   203,  4210,
           1063,   913,  2627,   532,  2534,   538,   463,  1136,   287,  1821,
          10935,   468,   327,   687,   386,  3459,  3769, 10248,  2534,   789,
            676,   530,  1408,  1824, 18757,  7429,  2534,    18,   203,  7796,
           1059,  2365,  6774,   863,   525,   502,   287, 36099,    16,  1063,
           8876,    16,   789,  1328,   505,  2881,  8654, 12509,  4846,   300,
          19255,   338,  1053, 18757, 32331,    17,  1457,  1925,   303,    18,
            203,  1813,  2496,  3430,    16,  3281,   338,  1358,  1821, 10935,
            386,  1349,   327,  1017, 20431,   960,  2807,  6477,     6,   419,
           1017, 27301,  3385, 34493,  3152,   203,  2907,   401,  5201,   735,
           3248,   287,  3041,    17, 26340,   296,  4532,     2]),
  'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1, 1, 1]),
  'labels': tensor(0)},
 {'input_ids': tensor([    0,    49,  6034,  2127,  6352,  3615,    61,  2906,    18,  4399,

# 6. Train Model

In [ ]:
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    logging_steps=10
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset
)

trainer.train()

/home/lenovo/Documents/School/Semester 6/PBA/kelompok-7-pba/.venv/lib/python3.14/site-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)